PyPie/urls.py
from django.conf.urls import url, include

from PyPie.admin import admin_site

urlpatterns = [
    url(r'^admin/', admin_site.urls),
    # url(r'^pie/', include('pie.urls')),
    url(r'^pie_run_order/', include('pie_run_order.urls')),
    url(r'', include('pie_run.urls')),
]

pie/urls.py
from django.conf.urls import url
from . import views

app_name = 'pie'
# urlpatterns = [
#     url(r'^$', views.index, name='index'),
#     url(r'^(?P<pie_run_id>[a-zA-Z0-9\-]+?)/$', views.pie_run, name='pie_run'),
# ]

pie_run/urls.py
from django.urls import path

from . import views

app_name = 'pie_run'
urlpatterns = [
    path('', views.index, name='index'),
    path('<uuid:pie_run_id>/', views.pie_run, name='pie_run'),
]

pie_run_order/urls.py
from django.urls import path

from . import views

app_name = 'pie_run_order'
urlpatterns = [
    path('details/<uuid:pk>/', views.DetailView.as_view(), name='details'),
    path('add/', views.add, name='add'),
]

pie/models.py
import uuid

from django.db import models


class Pie(models.Model):
    pie_id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return self.name

pie_run/models.py
import uuid

from django.db import models


class PieRun(models.Model):
    pie_run_id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

pie_run_order/models.py
import uuid

from django.db import models

from pie.models import Pie
from pie_run.models import PieRun


class PieRunOrder(models.Model):
    pie_run_order_id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    pie_run = models.ForeignKey(PieRun, on_delete=models.CASCADE)
    client_name = models.CharField(max_length=100)

    def __str__(self):
        return str(f"{self.pie_run} - {self.client_name}")


class PieRunOrderEntry(models.Model):
    pie_run_order_entry_id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    pie_run_order = models.ForeignKey(PieRunOrder, on_delete=models.CASCADE)
    pie = models.ForeignKey(Pie, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return str(F"{self.quantity} x {self.pie}")

pie/views.py
from django.shortcuts import render, get_object_or_404

pie_run/views.py
from django.shortcuts import render, get_object_or_404

from pie.models import Pie
from pie_run.models import PieRun
from pie_run_order.models import PieRunOrder


def index(request):
    pie_runs = PieRun.objects.all()
    context = {
        'title': 'Pie Runs',
        'pie_runs': pie_runs
    }
    return render(request, 'pie_run/index.html', context)


def pie_run(request, pie_run_id):
    pie_run = get_object_or_404(PieRun, pie_run_id=pie_run_id)
    pie_run_orders = PieRunOrder.objects.filter(pie_run_id=pie_run_id)
    pies = Pie.objects.all()
    context = {
        'title': f'Pie Run {pie_run}',
        'pie_run': pie_run,
        'pie_run_orders': pie_run_orders,
        'pies': pies,
    }
    return render(request, 'pie_run/pie-run.html', context)

pie_run_order/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic

from pie_run_order.models import PieRunOrder, PieRunOrderEntry


def add(request):
    pie_run_order = PieRunOrder(client_name=request.POST['client_name'],
                                pie_run_id=request.POST['pie_run_id'])
    pie_run_order.save()

    order_items = zip(request.POST.getlist("pie-id[]"),
                      request.POST.getlist("pie-count[]"))
    order_items = filter(lambda x: x[1] and int(x[1]) > 0, order_items)
    for pie_order in order_items:
        pie_run_order_entry = PieRunOrderEntry(pie_run_order=pie_run_order,
                                               pie_id=pie_order[0],
                                               quantity=pie_order[1])
        pie_run_order_entry.save()

    return redirect("pie_run_order:details", pk=pie_run_order.pie_run_order_id)


def details(request, pie_run_order_id):
    pie_run_order = get_object_or_404(PieRunOrder, pie_run_order_id=pie_run_order_id)
    pie_run_order_entries = PieRunOrderEntry.objects.filter(pie_run_order_id=pie_run_order_id)
    context = {
        "pie_run_order": pie_run_order,
        "pie_run_order_entries": pie_run_order_entries,
    }
    return render(request, "pie_run_order/details.html", context)


class DetailView(generic.DetailView):
    model = PieRunOrder
    context_object_name = "pie_run_order"
    template_name = "pie_run_order/details.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context["pie_run_order_entries"] = PieRunOrderEntry.objects.filter(pie_run_order=context["pie_run_order"])
        return context

pie_run/templates/pie_run/index.html
{% extends "base.html" %}

{% block content %}
<h1>Pie Runs</h1>
<ul>
    {% for pie_run in pie_runs %}
        <li>
            <a href="{% url 'pie_run:pie_run' pie_run.pie_run_id %}">{{ pie_run }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

pie_run/templates/pie_run/pie-run.html
{% extends "base.html" %}

{% block content %}
<h1>{{ pie_run }}</h1>

<h2>Add your order</h2>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'pie_run_order:add' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="pie_run_id" value="{{ pie_run.pie_run_id }}" />
    <label for="client_name">Your name:</label>
    <input type="text" name="client_name" required />
    {% for pie in pies %}
        <input type="hidden" name="pie-id[]" value="{{ pie.pie_id }}"/>
        <label for="pie-count[]">{{ pie.name }}</label>
        <input class="pie-input" name="pie-count[]" type="number"/>
    {% endfor %}
    <input type="submit" value="order" />
</form>

<h2>Orders</h2>
<ul>
    {% for pie_run_order in pie_run_orders %}
        <li>
            <a href="{% url 'pie_run_order:details' pie_run_order.pie_run_order_id %}">
                {{ pie_run_order }}
            </a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

pie_run_order/templates/pie_run_order/details.html
{% extends "base.html" %}

{% block content %}
<h1>Pie Run Order</h1>
<p>Client: {{ pie_run_order.client_name }}</p>
<h2>Items ordered:</h2>
<ul>
    {% for pie_run_order_entry in pie_run_order_entries %}
        <li>
            {{ pie_run_order_entry }}
        </li>
    {% endfor %}
</ul>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>header</p>
{% block content %}{% endblock %}
</body>
</html>